# Generated by Django 3.1.6 on 2021-02-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='discord_id',
            new_name='id',
        ),
    ]
