# Generated by Django 3.1.6 on 2021-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0004_auto_20210207_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='mode',
            field=models.CharField(choices=[('FRIENDLIES', 'Friendlies'), ('RANKED', 'Ranked')], default='FRIENDLIES', max_length=10),
        ),
    ]
