# Generated by Django 3.1.6 on 2021-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0005_arena_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CONFIRM', 'Confirmation'), ('PLAYING', 'Playing'), ('CLOSED', 'Closed')], default='WAITING', max_length=7),
        ),
    ]
