# Generated by Django 3.1.6 on 2021-02-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0008_auto_20210208_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='players',
            field=models.ManyToManyField(blank=True, through='smashbotspain.ArenaPlayer', to='smashbotspain.Player'),
        ),
    ]
