# Generated by Django 3.1.6 on 2021-02-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0009_auto_20210208_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaplayer',
            name='arena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.arena'),
        ),
        migrations.AlterField(
            model_name='arenaplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smashbotspain.player'),
        ),
    ]
