# Generated by Django 3.1.6 on 2021-02-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0011_auto_20210208_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
