# Generated by Django 3.1.6 on 2021-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0012_tier_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='channel_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
