# Generated by Django 3.1.6 on 2021-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0014_auto_20210209_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaplayer',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CONFIRMED', 'Confirmed'), ('PLAYING', 'Playing'), ('GGS', 'GGs'), ('INVITED', 'Invited')], max_length=10),
        ),
    ]
