# Generated by Django 3.1.6 on 2021-02-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0015_auto_20210209_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaplayer',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CONFIRMATION', 'Confirmation'), ('ACCEPTED', 'Accepted'), ('PLAYING', 'Playing'), ('GGS', 'GGs'), ('INVITED', 'Invited')], max_length=12),
        ),
    ]
