# Generated by Django 3.1.6 on 2021-02-20 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0017_auto_20210212_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='num_players',
        ),
        migrations.AlterField(
            model_name='arena',
            name='max_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
