# Generated by Django 3.1.6 on 2021-02-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0018_auto_20210220_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
