# Generated by Django 3.1.6 on 2021-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0020_auto_20210223_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='rejected_players',
            field=models.ManyToManyField(blank=True, related_name='rejected_set', to='smashbotspain.Player'),
        ),
    ]
