# Generated by Django 3.1.6 on 2021-02-26 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0022_auto_20210226_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
