# Generated by Django 3.1.6 on 2021-02-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0023_arena_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='messages',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.arena')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.tier')),
            ],
        ),
    ]
