# Generated by Django 3.1.6 on 2021-02-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0024_auto_20210226_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching'), ('WAITING', 'Waiting'), ('CONFIRMATION', 'Confirmation'), ('PLAYING', 'Playing'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='SEARCHING', max_length=12),
        ),
    ]
