# Generated by Django 3.1.6 on 2021-03-01 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0025_auto_20210228_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('guild', models.BigIntegerField(primary_key=True, serialize=False)),
                ('spam_channel', models.BigIntegerField()),
                ('flairing_channel', models.BigIntegerField()),
                ('friendlies_timeout', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(10)])),
                ('ggs_time', models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(10)])),
            ],
        ),
    ]
