# Generated by Django 3.1.6 on 2021-03-01 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0026_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ggs_time',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
