# Generated by Django 3.1.6 on 2021-03-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0027_auto_20210301_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Guild',
        ),
        migrations.RenameField(
            model_name='guild',
            old_name='guild',
            new_name='id',
        ),
    ]
