# Generated by Django 3.1.6 on 2021-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0029_auto_20210301_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='list_message',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
