# Generated by Django 3.1.6 on 2021-03-03 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0030_guild_list_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='friendlies_timeout',
            new_name='match_timeout',
        ),
        migrations.AddField(
            model_name='guild',
            name='cancel_time',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
