# Generated by Django 3.1.6 on 2021-03-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0031_auto_20210303_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.guild'),
        ),
    ]
