# Generated by Django 3.1.6 on 2021-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0033_auto_20210304_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tier',
        ),
        migrations.AddField(
            model_name='player',
            name='tiers',
            field=models.ManyToManyField(blank=True, to='smashbotspain.Tier'),
        ),
        migrations.AlterField(
            model_name='main',
            name='main',
            field=models.CharField(choices=[('MAIN', 'Main'), ('SECOND', 'Second'), ('POCKET', 'Pocket')], max_length=10),
        ),
    ]
