# Generated by Django 3.1.6 on 2021-03-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0034_auto_20210312_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='main',
            new_name='status',
        ),
    ]
