# Generated by Django 3.1.6 on 2021-03-12 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0035_auto_20210312_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.guild'),
        ),
        migrations.AddField(
            model_name='guild',
            name='role_message_time',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
