# Generated by Django 3.1.6 on 2021-03-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0036_auto_20210312_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='discord_id',
            field=models.BigIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='discord_id',
            field=models.BigIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tier',
            name='discord_id',
            field=models.BigIntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
