# Generated by Django 3.1.6 on 2021-03-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0037_auto_20210314_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='regions',
            field=models.ManyToManyField(blank=True, to='smashbotspain.Region'),
        ),
    ]
