# Generated by Django 3.1.6 on 2021-03-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0038_auto_20210314_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='characters',
            field=models.ManyToManyField(blank=True, through='smashbotspain.Main', to='smashbotspain.Character'),
        ),
    ]
