# Generated by Django 3.1.6 on 2021-03-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0040_auto_20210314_0418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('discord_id',), ('name', 'guild')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('discord_id',), ('name', 'guild')},
        ),
    ]
