# Generated by Django 3.1.6 on 2021-03-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0041_auto_20210314_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='character',
        ),
        migrations.RemoveField(
            model_name='player',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='emoji',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CharacterRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.character')),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.guild')),
            ],
            options={
                'unique_together': {('character', 'guild'), ('discord_id',)},
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='guild',
        ),
        migrations.AddField(
            model_name='main',
            name='character_role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.characterrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='character_roles',
            field=models.ManyToManyField(blank=True, through='smashbotspain.Main', to='smashbotspain.CharacterRole'),
        ),
    ]
