# Generated by Django 3.1.6 on 2021-03-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0042_auto_20210315_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='regions',
        ),
        migrations.AddField(
            model_name='region',
            name='emoji',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RegionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField()),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.guild')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.region')),
            ],
            options={
                'unique_together': {('region', 'guild'), ('discord_id',)},
            },
        ),
        migrations.RemoveField(
            model_name='region',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='guild',
        ),
        migrations.AddField(
            model_name='player',
            name='region_roles',
            field=models.ManyToManyField(blank=True, to='smashbotspain.RegionRole'),
        ),
    ]
