# Generated by Django 3.1.6 on 2021-03-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0044_auto_20210316_0352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterrole',
            unique_together={('character', 'guild'), ('discord_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='regionrole',
            unique_together={('region', 'guild'), ('discord_id',)},
        ),
    ]
