# Generated by Django 3.1.6 on 2021-03-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0045_auto_20210316_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='emoji',
            field=models.CharField(max_length=80),
        ),
    ]
