# Generated by Django 3.1.6 on 2021-03-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0046_auto_20210316_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
