# Generated by Django 3.1.6 on 2021-03-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0048_auto_20210320_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='channel_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
