# Generated by Django 3.1.6 on 2021-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0049_auto_20210321_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='discord_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='guild',
            unique_together={('discord_id',)},
        ),
    ]
