# Generated by Django 3.1.6 on 2021-03-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0051_auto_20210324_0040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('discord_id',)},
        ),
    ]
