# Generated by Django 3.1.6 on 2021-03-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0052_auto_20210324_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arena',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching'), ('WAITING', 'Waiting'), ('CONFIRMATION', 'Confirmation'), ('PLAYING', 'Playing')], default='SEARCHING', max_length=12),
        ),
    ]
