# Generated by Django 3.1.6 on 2021-04-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0054_auto_20210407_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='game_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smashbotspain.gameset'),
        ),
    ]
