# Generated by Django 3.1.6 on 2021-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0055_arena_game_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='ranked_channel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='ranked_message',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
