# Generated by Django 3.1.6 on 2021-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0056_auto_20210703_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
