# Generated by Django 3.1.6 on 2021-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0057_message_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mode',
            field=models.CharField(choices=[('FRIENDLIES', 'Friendlies'), ('RANKED', 'Ranked')], default='FRIENDLIES', max_length=10),
        ),
    ]
