# Generated by Django 3.1.6 on 2021-07-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0059_auto_20210704_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier', to='smashbotspain.tier'),
        ),
    ]
