# Generated by Django 3.1.6 on 2021-07-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0060_arena_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='game_set',
        ),
        migrations.AddField(
            model_name='gameset',
            name='arena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smashbotspain.arena'),
        ),
    ]
