# Generated by Django 3.1.6 on 2021-07-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0061_auto_20210707_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('STARTER', 'Starter'), ('COUNTERPICK', 'Counterpick')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StageGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NONE', 'None'), ('BAN', 'Ban'), ('PICK', 'Pick')], default='NONE', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.game')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smashbotspain.stage')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='strikes',
            field=models.ManyToManyField(related_name='strikes', through='smashbotspain.StageGame', to='smashbotspain.Stage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smashbotspain.stage'),
        ),
    ]
