# Generated by Django 3.1.6 on 2021-07-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0062_auto_20210707_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='strikes',
        ),
        migrations.DeleteModel(
            name='StageGame',
        ),
    ]
