# Generated by Django 3.1.6 on 2021-07-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0064_game_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_character',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='winner',
        ),
    ]
