# Generated by Django 3.1.6 on 2021-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0065_auto_20210708_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameset',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
