# Generated by Django 3.1.6 on 2021-07-09 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0066_auto_20210709_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
