# Generated by Django 3.1.6 on 2021-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0069_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='threshold',
            field=models.IntegerField(default=1200),
        ),
    ]
