# Generated by Django 3.1.6 on 2021-07-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0070_tier_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='promotion_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='promotion_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
