# Generated by Django 3.1.6 on 2021-07-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0071_auto_20210711_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_set', to='smashbotspain.player'),
        ),
    ]
