# Generated by Django 3.1.6 on 2021-07-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0072_auto_20210711_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='leaderboard_channel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='leaderboard_message',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
