# Generated by Django 3.1.6 on 2021-08-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smashbotspain', '0073_auto_20210712_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='promotion_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
